In [ ]:
#Tile

In [1]:
#Read csv files
import pandas as pd
csv_path = "Resources/global_power_plant_database.csv"
global_pwrplant = pd.read_csv(csv_path)
csv_path1 = "Resources/API_NY.GDP.MKTP.CD_DS2_en_csv_v2_4701247.csv"
gdp_data = pd.read_csv(csv_path1,skiprows=4)
csv_path2 = "Resources/Human Development Index - Full.csv"
hdi_data = pd.read_csv(csv_path2)

/var/folders/ng/41b1kp4n0wg3hvfwdd1fdzzm0000gn/T/ipykernel_98660/403541752.py:4: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  global_pwrplant = pd.read_csv(csv_path)

In [44]:
#3 merged dataframes
full_data_merge = pd.merge(power_gdp_dframe,hdi_data,left_on="country_long",right_on="Country")

In [ ]:
#Cleaned dataframe

In [17]:
#vis 
global_pwrplant

,country,country_long,name,gppd_idnr,capacity_mw,latitude,longitude,primary_fuel,other_fuel1,other_fuel2,...,estimated_generation_gwh_2013,estimated_generation_gwh_2014,estimated_generation_gwh_2015,estimated_generation_gwh_2016,estimated_generation_gwh_2017,estimated_generation_note_2013,estimated_generation_note_2014,estimated_generation_note_2015,estimated_generation_note_2016,estimated_generation_note_2017
0,AFG,Afghanistan,Kajaki Hydroelectric Power Plant Afghanistan,GEODB0040538,33.0,32.3220,65.1190,Hydro,NaN,NaN,...,123.77,162.90,97.39,137.76,119.50,HYDRO-V1,HYDRO-V1,HYDRO-V1,HYDRO-V1,HYDRO-V1
1,AFG,Afghanistan,Kandahar DOG,WKS0070144,10.0,31.6700,65.7950,Solar,NaN,NaN,...,18.43,17.48,18.25,17.70,18.29,SOLAR-V1-NO-AGE,SOLAR-V1-NO-AGE,SOLAR-V1-NO-AGE,SOLAR-V1-NO-AGE,SOLAR-V1-NO-AGE
2,AFG,Afghanistan,Kandahar JOL,WKS0071196,10.0,31.6230,65.7920,Solar,NaN,NaN,...,18.64,17.58,19.10,17.62,18.72,SOLAR-V1-NO-AGE,SOLAR-V1-NO-AGE,SOLAR-V1-NO-AGE,SOLAR-V1-NO-AGE,SOLAR-V1-NO-AGE
3,AFG,Afghanistan,Mahipar Hydroelectric Power Plant Afghanistan,GEODB0040541,66.0,34.5560,69.4787,Hydro,NaN,NaN,...,225.06,203.55,146.90,230.18,174.91,HYDRO-V1,HYDRO-V1,HYDRO-V1,HYDRO-V1,HYDRO-V1
4,AFG,Afghanistan,Naghlu Dam Hydroelectric Power Plant Afghanistan,GEODB0040534,100.0,34.6410,69.7170,Hydro,NaN,NaN,...,406.16,357.22,270.99,395.38,350.80,HYDRO-V1,HYDRO-V1,HYDRO-V1,HYDRO-V1,HYDRO-V1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34931,ZMB,Zambia,Ndola,WRI1022386,50.0,-12.9667,28.6333,Oil,NaN,NaN,...,NaN,NaN,NaN,NaN,183.79,NO-ESTIMATION,NO-ESTIMATION,NO-ESTIMATION,NO-ESTIMATION,CAPACITY-FACTOR-V1
34932,ZMB,Zambia,Nkana,WRI1022384,20.0,-12.8167,28.2000,Oil,NaN,NaN,...,NaN,NaN,NaN,NaN,73.51,NO-ESTIMATION,NO-ESTIMATION,NO-ESTIMATION,NO-ESTIMATION,CAPACITY-FACTOR-V1
34933,ZMB,Zambia,Victoria Falls,WRI1022380,108.0,-17.9167,25.8500,Hydro,NaN,NaN,...,575.78,575.78,548.94,579.90,578.32,HYDRO-V1,HYDRO-V1,HYDRO-V1,HYDRO-V1,HYDRO-V1
34934,ZWE,Zimbabwe,Hwange Coal Power Plant Zimbabwe,GEODB0040404,920.0,-18.3835,26.4700,Coal,NaN,NaN,...,NaN,NaN,NaN,NaN,2785.10,NO-ESTIMATION,NO-ESTIMATION,NO-ESTIMATION,NO-ESTIMATION,CAPACITY-FACTOR-V1
34935,ZWE,Zimbabwe,Kariba Dam South Hydroelectric Power Station Z...,GEODB0003803,750.0,-16.5222,28.7619,Hydro,NaN,NaN,...,3999.75,3999.75,3745.02,3428.65,3960.24,HYDRO-V1,HYDRO-V1,HYDRO-V1,HYDRO-V1,HYDRO-V1

In [45]:
country_grouped_df=global_pwrplant.groupby(["country_long"]).sum()
country_grouped_df

,capacity_mw,latitude,longitude,commissioning_year,year_of_capacity_data,generation_gwh_2013,generation_gwh_2014,generation_gwh_2015,generation_gwh_2016,generation_gwh_2017,generation_gwh_2018,generation_gwh_2019,estimated_generation_gwh_2013,estimated_generation_gwh_2014,estimated_generation_gwh_2015,estimated_generation_gwh_2016,estimated_generation_gwh_2017
country_long,,,,,,,,,,,,,,,,,
Afghanistan,300.550,304.3886,613.8641,0.0,14119.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,996.05,917.21,682.89,977.53,828.08
Albania,1529.000,331.4694,158.6606,13771.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,5259.64,3688.06,4176.21,5449.36,4608.91
Algeria,15873.800,1993.4829,190.8176,42029.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,30.81,1178.55,1165.00,1194.03,64568.81
Angola,1071.180,-154.2466,201.6706,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,2330.55,2907.13,2809.78,2458.13,3054.59
Antarctica,7.600,-155.6898,333.3876,1981.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Vietnam,41350.490,3834.7813,25181.1428,335500.0,0.0,0.0,0.0,0.0,66775.12,0.0,0.0,0.0,66464.51,65622.52,57653.54,65591.03,178034.30
Western Sahara,23.400,23.6816,-15.9594,0.0,2017.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00
Yemen,1045.000,97.8290,311.0468,11915.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.00,0.00,0.00,0.00,2807.33
Zambia,2689.337,-218.5862,416.9842,5965.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,10280.57,10280.29,10060.97,10160.57,12843.60
Zimbabwe,1670.000,-34.9057,55.2319,0.0,4034.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,3999.75,3999.75,3745.02,3428.65,6745.34

In [46]:
# 1-Top 5 energy producing countries all energy sources combined
country_grouped_df.sort_values(by=["capacity_mw"],ascending=False).head(5)

,capacity_mw,latitude,longitude,commissioning_year,year_of_capacity_data,generation_gwh_2013,generation_gwh_2014,generation_gwh_2015,generation_gwh_2016,generation_gwh_2017,generation_gwh_2018,generation_gwh_2019,estimated_generation_gwh_2013,estimated_generation_gwh_2014,estimated_generation_gwh_2015,estimated_generation_gwh_2016,estimated_generation_gwh_2017
country_long,,,,,,,,,,,,,,,,,
China,1415067.380,149201.2197,463471.0725,2.178010e+06,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,745110.74,929531.06,907931.27,1010182.31,6193117.75
United States of America,1204638.050,383563.5670,-925226.5060,1.960284e+07,19763991.0,3.474741e+06,3.456613e+06,3.573784e+06,3.512827e+06,3.529342e+06,3.634343e+06,4.094667e+06,525398.25,548595.41,524676.45,593993.41,4653165.24
India,316088.546,32847.3501,122385.7519,9.905180e+05,993348.0,0.000000e+00,9.670936e+05,1.022812e+06,1.065429e+06,1.115205e+06,1.159224e+06,0.000000e+00,232632.73,207440.38,225837.15,188164.86,1434479.65
Russia,228220.050,29836.4145,33486.1996,5.408830e+05,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,173220.57,142065.05,158038.68,156471.21,979376.03
Japan,215365.850,18715.0296,71293.1587,1.774220e+05,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,84033.30,68290.13,105404.81,83209.60,998572.01

In [47]:
# 2-Top 5 countries with the most installed power generation facilities (all energy sources combined)
installed_pwr=global_pwrplant.groupby(["country_long"]).count()
installed_pwr

,country,name,gppd_idnr,capacity_mw,latitude,longitude,primary_fuel,other_fuel1,other_fuel2,other_fuel3,...,estimated_generation_gwh_2013,estimated_generation_gwh_2014,estimated_generation_gwh_2015,estimated_generation_gwh_2016,estimated_generation_gwh_2017,estimated_generation_note_2013,estimated_generation_note_2014,estimated_generation_note_2015,estimated_generation_note_2016,estimated_generation_note_2017
country_long,,,,,,,,,,,,,,,,,,,,,
Afghanistan,9,9,9,9,9,9,9,0,0,0,...,8,8,8,8,8,9,9,9,9,9
Albania,8,8,8,8,8,8,8,0,0,0,...,7,7,7,7,7,8,8,8,8,8
Algeria,59,59,59,59,59,59,59,13,0,0,...,1,28,28,28,59,59,59,59,59,59
Angola,14,14,14,14,14,14,14,0,0,0,...,5,5,5,5,14,14,14,14,14,14
Antarctica,2,2,2,2,2,2,2,0,0,0,...,0,0,0,0,0,2,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Vietnam,236,236,236,236,236,236,236,0,0,0,...,190,190,190,190,234,236,236,236,236,236
Western Sahara,1,1,1,1,1,1,1,0,0,0,...,0,0,0,0,0,1,1,1,1,1
Yemen,7,7,7,7,7,7,7,0,0,0,...,0,0,0,0,7,7,7,7,7,7
Zambia,15,15,15,15,15,15,15,0,0,0,...,6,6,6,6,14,15,15,15,15,15
Zimbabwe,2,2,2,2,2,2,2,0,0,0,...,1,1,1,1,2,2,2,2,2,2

In [48]:
# !clean
installed_pwr.sort_values(by=["capacity_mw"],ascending=False).head(5)

,country,name,gppd_idnr,capacity_mw,latitude,longitude,primary_fuel,other_fuel1,other_fuel2,other_fuel3,...,estimated_generation_gwh_2013,estimated_generation_gwh_2014,estimated_generation_gwh_2015,estimated_generation_gwh_2016,estimated_generation_gwh_2017,estimated_generation_note_2013,estimated_generation_note_2014,estimated_generation_note_2015,estimated_generation_note_2016,estimated_generation_note_2017
country_long,,,,,,,,,,,,,,,,,,,,,
United States of America,9833,9833,9833,9833,9833,9833,9833,1429,269,92,...,2603,2901,3238,3594,9531,9833,9833,9833,9833,9833
China,4235,4235,4235,4235,4235,4235,4235,1,0,0,...,2263,2263,2263,2263,4235,4235,4235,4235,4235,4235
United Kingdom,2751,2751,2751,2751,2751,2751,2751,2,0,0,...,1289,1289,1289,1289,2480,2751,2751,2751,2751,2751
Brazil,2360,2360,2360,2360,2360,2360,2360,0,0,0,...,799,814,922,1024,1916,2360,2360,2360,2360,2360
France,2155,2155,2155,2155,2155,2155,2155,0,0,0,...,1246,1246,1246,1246,2005,2155,2155,2155,2155,2155

In [9]:
fuel_grouped_df = global_pwrplant.groupby(['country_long','primary_fuel']).sum()
fuel_grouped_df.head(5)

                           capacity_mw  latitude  longitude  \
country_long primary_fuel
Afghanistan  Gas                 42.00   34.5638    69.1134
             Hydro              238.55  206.5318   413.1637
             Solar               20.00   63.2930   131.5870
Albania      Hydro             1431.00  290.9820   139.2266
             Other               98.00   40.4874    19.4340

                           commissioning_year  year_of_capacity_data  \
country_long primary_fuel
Afghanistan  Gas                          0.0                 2017.0
             Hydro                        0.0                12102.0
             Solar                        0.0                    0.0
Albania      Hydro                    13771.0                    0.0
             Other                        0.0                    0.0

                           generation_gwh_2013  generation_gwh_2014  \
country_long primary_fuel
Afghanistan  Gas                           0.0                  0.0
             Hydro                         0.0                  0.0
             Solar                         0.0                  0.0
Albania      Hydro                         0.0                  0.0
             Other                         0.0                  0.0

                           generation_gwh_2015  generation_gwh_2016  \
country_long primary_fuel
Afghanistan  Gas                           0.0                  0.0
             Hydro                         0.0                  0.0
             Solar                         0.0                  0.0
Albania      Hydro                         0.0                  0.0
             Other                         0.0                  0.0

                           generation_gwh_2017  generation_gwh_2018  \
country_long primary_fuel
Afghanistan  Gas                           0.0                  0.0
             Hydro                         0.0                  0.0
             Solar                         0.0                  0.0
Albania      Hydro                         0.0                  0.0
             Other                         0.0                  0.0

                           generation_gwh_2019  estimated_generation_gwh_2013  \
country_long primary_fuel
Afghanistan  Gas                           0.0                           0.00
             Hydro                         0.0                         958.98
             Solar                         0.0                          37.07
Albania      Hydro                         0.0                        5259.64
             Other                         0.0                           0.00

                           estimated_generation_gwh_2014  \
country_long primary_fuel
Afghanistan  Gas                                    0.00
             Hydro                                882.15
             Solar                                 35.06
Albania      Hydro                               3688.06
             Other                                  0.00

                           estimated_generation_gwh_2015  \
country_long primary_fuel
Afghanistan  Gas                                    0.00
             Hydro                                645.54
             Solar                                 37.35
Albania      Hydro                               4176.21
             Other                                  0.00

                           estimated_generation_gwh_2016  \
country_long primary_fuel
Afghanistan  Gas                                    0.00
             Hydro                                942.21
             Solar                                 35.32
Albania      Hydro                               5449.36
             Other                                  0.00

                           estimated_generation_gwh_2017
country_long primary_fuel
Afghanistan  Gas                                    0.00
             Hydro                                791.07
             Solar                                 37.01
Albania      Hydro                               4608.91
             Other                                  0.00

In [14]:
solar_df = global_pwrplant.loc[global_pwrplant['primary_fuel']=="Solar"]
solar_df

grouped_solar_df = solar_df.groupby('country_long').sum()
grouped_solar_df.sort_values(by=['capacity_mw'], ascending = False).head(5)

,capacity_mw,latitude,longitude,commissioning_year,year_of_capacity_data,generation_gwh_2013,generation_gwh_2014,generation_gwh_2015,generation_gwh_2016,generation_gwh_2017,generation_gwh_2018,generation_gwh_2019,estimated_generation_gwh_2013,estimated_generation_gwh_2014,estimated_generation_gwh_2015,estimated_generation_gwh_2016,estimated_generation_gwh_2017
country_long,,,,,,,,,,,,,,,,,
China,54801.82000,49362.0550,138441.1031,2.011000e+03,0.0,0.00000,0.00000,0.00000,0.0000,0.00000,0.00000,0.00000,87670.03,87336.23,87990.05,88318.28,88735.93
United States of America,37970.35000,124947.2060,-298336.1477,6.605847e+06,6610206.0,8832.07371,16985.15013,24659.52788,35735.0741,53028.46626,63247.93256,71652.44288,5808.64,15091.25,21957.04,27923.21,73706.07
India,25549.10000,17559.6743,64833.8031,8.051000e+03,0.0,0.00000,0.00000,0.00000,0.0000,0.00000,0.00000,0.00000,52571.42,52922.01,53815.01,54481.86,53634.13
United Kingdom,8674.99798,60757.0388,-2451.2575,0.000000e+00,0.0,0.00000,0.00000,0.00000,0.0000,0.00000,0.00000,0.00000,12821.65,12986.70,12931.23,12992.32,13191.77
Germany,6770.56288,37562.6115,8385.6215,0.000000e+00,0.0,0.00000,0.00000,0.00000,0.0000,0.00000,0.00000,0.00000,9584.61,9920.04,9948.17,9945.53,9888.06

In [27]:
global_pwrplant

,country,country_long,name,gppd_idnr,capacity_mw,latitude,longitude,primary_fuel,other_fuel1,other_fuel2,...,estimated_generation_gwh_2013,estimated_generation_gwh_2014,estimated_generation_gwh_2015,estimated_generation_gwh_2016,estimated_generation_gwh_2017,estimated_generation_note_2013,estimated_generation_note_2014,estimated_generation_note_2015,estimated_generation_note_2016,estimated_generation_note_2017
0,AFG,Afghanistan,Kajaki Hydroelectric Power Plant Afghanistan,GEODB0040538,33.0,32.3220,65.1190,Hydro,NaN,NaN,...,123.77,162.90,97.39,137.76,119.50,HYDRO-V1,HYDRO-V1,HYDRO-V1,HYDRO-V1,HYDRO-V1
1,AFG,Afghanistan,Kandahar DOG,WKS0070144,10.0,31.6700,65.7950,Solar,NaN,NaN,...,18.43,17.48,18.25,17.70,18.29,SOLAR-V1-NO-AGE,SOLAR-V1-NO-AGE,SOLAR-V1-NO-AGE,SOLAR-V1-NO-AGE,SOLAR-V1-NO-AGE
2,AFG,Afghanistan,Kandahar JOL,WKS0071196,10.0,31.6230,65.7920,Solar,NaN,NaN,...,18.64,17.58,19.10,17.62,18.72,SOLAR-V1-NO-AGE,SOLAR-V1-NO-AGE,SOLAR-V1-NO-AGE,SOLAR-V1-NO-AGE,SOLAR-V1-NO-AGE
3,AFG,Afghanistan,Mahipar Hydroelectric Power Plant Afghanistan,GEODB0040541,66.0,34.5560,69.4787,Hydro,NaN,NaN,...,225.06,203.55,146.90,230.18,174.91,HYDRO-V1,HYDRO-V1,HYDRO-V1,HYDRO-V1,HYDRO-V1
4,AFG,Afghanistan,Naghlu Dam Hydroelectric Power Plant Afghanistan,GEODB0040534,100.0,34.6410,69.7170,Hydro,NaN,NaN,...,406.16,357.22,270.99,395.38,350.80,HYDRO-V1,HYDRO-V1,HYDRO-V1,HYDRO-V1,HYDRO-V1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34931,ZMB,Zambia,Ndola,WRI1022386,50.0,-12.9667,28.6333,Oil,NaN,NaN,...,NaN,NaN,NaN,NaN,183.79,NO-ESTIMATION,NO-ESTIMATION,NO-ESTIMATION,NO-ESTIMATION,CAPACITY-FACTOR-V1
34932,ZMB,Zambia,Nkana,WRI1022384,20.0,-12.8167,28.2000,Oil,NaN,NaN,...,NaN,NaN,NaN,NaN,73.51,NO-ESTIMATION,NO-ESTIMATION,NO-ESTIMATION,NO-ESTIMATION,CAPACITY-FACTOR-V1
34933,ZMB,Zambia,Victoria Falls,WRI1022380,108.0,-17.9167,25.8500,Hydro,NaN,NaN,...,575.78,575.78,548.94,579.90,578.32,HYDRO-V1,HYDRO-V1,HYDRO-V1,HYDRO-V1,HYDRO-V1
34934,ZWE,Zimbabwe,Hwange Coal Power Plant Zimbabwe,GEODB0040404,920.0,-18.3835,26.4700,Coal,NaN,NaN,...,NaN,NaN,NaN,NaN,2785.10,NO-ESTIMATION,NO-ESTIMATION,NO-ESTIMATION,NO-ESTIMATION,CAPACITY-FACTOR-V1
34935,ZWE,Zimbabwe,Kariba Dam South Hydroelectric Power Station Z...,GEODB0003803,750.0,-16.5222,28.7619,Hydro,NaN,NaN,...,3999.75,3999.75,3745.02,3428.65,3960.24,HYDRO-V1,HYDRO-V1,HYDRO-V1,HYDRO-V1,HYDRO-V1

In [35]:
global_pwrplant['primary_fuel'].value_counts()

fuel_list = ['Solar', 'Hydro', 'Wind', 'Gas', 'Coal', 'Oil', 'Biomass',            
'Waste',              
'Nuclear',             
'Geothermal',          
'Storage',             
'Other',               
'Cogeneration',         
'Petcoke',              
'Wave and Tidal']

solar_df = global_pwrplant.loc[global_pwrplant['primary_fuel']=="Solar"]
solar_df

grouped_solar_df = solar_df.groupby('country_long').sum()
grouped_solar_df.sort_values(by=['capacity_mw'], ascending = False).head(5)

# # def group_fuel(fuel_type):
# #     fuel_type_df = global_pwrplant.loc[global_pwrplant['primary_fuel']=={fuel_type}]
# #     grouped_fuel_df = fuel_type_df.groupby('country_long').sum()
# #     print(grouped_fuel_df.sort_values(by=['capacity_mw'], ascending = False).head(5))

global_pwrplant_reduced = global_pwrplant[['country_long', 'capacity_mw', 'primary_fuel']]

global_pwrplant_reduced

for fuel_type in fuel_list:
    def group_fuel(fuel_type):
        fuel_type_df = global_pwrplant_reduced.loc[global_pwrplant_reduced['primary_fuel']==fuel_type]
        grouped_fuel_df = fuel_type_df.groupby('country_long').sum()
        print("    ")
        print("-----")
        print(fuel_type)
        print(grouped_fuel_df.sort_values(by=['capacity_mw'], ascending = False).head(5))
    
    group_fuel(fuel_type)

-----
Solar
                          capacity_mw
country_long
China                     54801.82000
United States of America  37970.35000
India                     25549.10000
United Kingdom             8674.99798
Germany                    6770.56288

-----
Hydro
                          capacity_mw
country_long
China                     259025.6000
United States of America  101656.9000
Brazil                     98039.3839
Canada                     80683.0000
Russia                     45591.4400

-----
Wind
                          capacity_mw
country_long
United States of America  104476.9000
China                      50990.3600
United Kingdom             23202.4815
Canada                     12133.8000
Spain                      11337.3800

-----
Gas
                          capacity_mw
country_long
United States of America    546435.80
Russia                      106722.62
China                        59774.50
Japan                        53362.75
Italy                        38570.65

-----
Coal
                          capacity_mw
country_long
China                       955718.00
United States of America    249149.10
India                       204919.22
Germany                      47772.90
Russia                       46072.22

-----
Oil
                          capacity_mw
country_long
Saudi Arabia                 49702.43
Japan                        44120.20
United States of America     37143.40
Mexico                       11522.40
Iran                         11310.60

-----
Biomass
                          capacity_mw
country_long
Brazil                     12843.8146
United States of America    5123.2000
Canada                      2741.9000
Finland                     2180.4400
Germany                     1655.3000

-----
Waste
                          capacity_mw
country_long
United States of America     9768.500
United Kingdom               1885.600
Germany                      1588.800
Spain                         388.054
Belgium                       223.400

-----
Nuclear
                          capacity_mw
country_long
United States of America     104233.1
France                        63130.0
Japan                         42537.0
China                         33402.0
Russia                        28168.0

-----
Geothermal
                          capacity_mw
country_long
United States of America       3889.2
Philippines                    1848.2
Indonesia                      1342.0
Mexico                          903.6
Italy                           857.0

-----
Storage
                          capacity_mw
country_long
United Kingdom                  896.7
United States of America        815.6

-----
Other
                          capacity_mw
country_long
Argentina                     1324.46
Germany                        756.90
United States of America       572.40
Italy                          384.60
Finland                        282.50

-----
Cogeneration
                          capacity_mw
country_long
United Kingdom                 3006.0
United States of America       1042.0

-----
Petcoke
                          capacity_mw
country_long
United States of America    2361.6000
Chile                         62.9775

-----
Wave and Tidal
                capacity_mw
country_long
South Korea           254.0
France                240.0
United Kingdom         38.2
Canada                 20.0